#cloud-config

hostname: coreos
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKtaFQuj4nvKmEq47SVtIW4AP7MM4Lt4rsafydHsyDgaAZooUqpAU6fBZZ0LeeCCwZ4Cs4/8cAxVlIxqlxa5MoVkFevIGtNsqcF9wyJ/3Y/Gmhjp6grylTZB4qIq/V+IpOQjRKkQxomByUp3A32XE4sZ95qL706V5AJusxmYQAX4mA26KWbYYDhm9e+ZP0yvbJVniDQ7/8DTH45e01QgEJpgi7rvWif6b1UaSEMBE71tKFFmVdqQjFm9GTo6e1nPo5cVSzijWmFdyiiaWKemSUHLpa5YJlH2tbzySMhRuKRoCZkfe0eOqqGFx68Cm8UOWCsZ38Ls2CPmE+Nb81HNmv

coreos:
  # All of our docker services are initially disabled (enable: false). We don't want
  # them to start before the machine is provisioned with the images. If we do start them
  # before image provisioning, the docker daemon will attempt to download the images,
  # something we don't want.
  #
  # The services are enabled after uploading the images. See template.json.
  units:
  - name: docker-mongo.service
    content: |
      [Unit]
      Description=Mongo Container
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      RestartSec=10s
      ExecStartPre=-/usr/bin/docker kill mongo
      ExecStartPre=-/usr/bin/docker rm mongo
      ExecStart=/usr/bin/docker run --rm --name mongo -p 27017:27017 -v /var/lib/mongo/data:/data/db mongo:2.7.7

      [Install]
      WantedBy=multi-user.target

  - name: docker-postgres.service
    content: |
      [Unit]
      Description=Postgres Container
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      RestartSec=10s
      ExecStartPre=-/usr/bin/docker kill postgres
      ExecStartPre=-/usr/bin/docker rm postgres
      ExecStart=/usr/bin/docker run --rm --name postgres -p 5432:5432 -v /var/lib/postgresql/data:/var/lib/postgresql/data postgres:9.4

      [Install]
      WantedBy=multi-user.target

  - name: docker-redis.service
    content: |
      [Unit]
      Description=Redis Container
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      RestartSec=10s
      ExecStartPre=-/usr/bin/docker kill redis
      ExecStartPre=-/usr/bin/docker rm redis
      ExecStart=/usr/bin/docker run --rm --name redis -p 6379:6379 -v /var/lib/redis/data:/data redis:2.8.17 redis-server --appendonly yes

      [Install]
      WantedBy=multi-user.target
  - name: docker-metarepo.service
    content: |
      [Unit]
      Description=Metarepo
      After=docker-postgres.service
      After=docker-mongo.service
      Requires=docker-postgres.service
      Requires=docker-mongo.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      RestartSec=10s
      ExecStartPre=-/usr/bin/docker kill metarepo
      ExecStartPre=-/usr/bin/docker rm metarepo
      ExecStart=/home/core/images/start-metarepo.sh 6d04e8c8b9f1311972e255c24feefcd85c210376.squash

      [Install]
      WantedBy=multi-user.target

  - name: docker-repos.service
    content: |
      [Unit]
      Description=Repos
      After=docker-redis.service
      After=docker-mongo.service
      After=docker-metarepo.service
      Requires=docker-redis.service
      Requires=docker-mongo.service
      Requires=docker-metarepo.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      RestartSec=10s
      ExecStartPre=-/usr/bin/docker kill repos
      ExecStartPre=-/usr/bin/docker rm repos
      ExecStart=/home/core/images/start-repos.sh 1901ec832fb0978571803670f4808923f048fb1c.squash

      [Install]
      WantedBy=multi-user.target

  - name: docker-cucumber-pro.service
    content: |
      [Unit]
      Description=Cucumber Pro
      After=docker-redis.service
      After=docker-mongo.service
      After=docker-metarepo.service
      After=docker-repos.service
      Requires=docker-redis.service
      Requires=docker-mongo.service
      Requires=docker-metarepo.service
      Requires=docker-repos.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      RestartSec=10s
      ExecStartPre=-/usr/bin/docker kill cucumber-pro
      ExecStartPre=-/usr/bin/docker rm cucumber-pro
      ExecStart=/home/core/images/start-cucumber-pro.sh e12bbe4c4d73402a3947b93ee9338eb9cd44e9f2.squash

      [Install]
      WantedBy=multi-user.target
